# Generated by Django 4.1.6 on 2023-02-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=101)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/pictures/')),
            ],
        ),
    ]
